import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useMemo, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [icons, setIcons] = useState<string[]>([]);
  const [query, setQuery] = useState("");

  useMemo(async () => {
    // make sure query is longer than 2
    if (query.length > 2) {
      const res = await fetch(`/api/hello?q=${query.toLowerCase()}`);
      const { icons }: { icons: string[] } = await res.json();
      setIcons(icons);
    } else {
      setIcons([]);
    }
  }, [query]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`min-h-screen flex flex-col items-center justify-center ${inter.className}`}
      >
        <input
          className="border border-gray-300 rounded-full py-4 pl-6 text-base w-screen max-w-lg"
          placeholder="Search Icons"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />

        <ul className="grid grid-cols-8 mt-8 gap-4">
          {icons.map((icon) => (
            <li key={icon} className="bg-white border rounded p-4">
              <Image src={`/svgs/${icon}.svg`} width={28} height={28} alt="" />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
